pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.5'
                }
            }
            steps {
                echo 'running build stage'
                sh 'python -m py_compile agileStyle.py'
            }
        }
 
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                echo 'running test stage'
                sh 'pytest --verbose --junit-xml test-reports/results.xml sources/AgileStyleTest.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
                           
                           
    }      
    
}
