pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                echo 'running build stage'
                sh 'python -m py_compile agileStyle.py'
            }
        }
 
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                echo 'running test stage'
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/AgileStyleTest.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deploy') {
               agent {
                   docker {
                       reuseNode true
                       image ‘nginx’
                   }
               }
               steps {
                    echo "Docker Created"
                     }
         }
                           
                           
    }      
    
}
